sonar.projectKey=Kasia-Sikora_shopping-list-manager
sonar.organization=kasia-sikora

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# hook your Vitest coverage into Sonar (you already emit lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.config.*,**/dist/**,.configs/**,**/__mocks__/**

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=shopping-list-manager
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8